### ISSUE TITLE
JS preset for React / React Native

### ISSUE THREAD

**Issue by Andreyco** [mrmrs/colors#102]
Would be great if we could get preset for React / React Native projects.
In such projects pure Javascript definitions would be the best fit.

If you are open to PR, I could work on this.

**Comment by mrmrs** [comment]
Is there a way to make this more interoperable across more js projects? 
https://github.com/mrmrs/colors/blob/master/js/colors.js

Or do you think it would be good to have different implementations accounting for how various js frameworks can consume this?

**Comment by Andreyco** [comment]
Sorry, found that file later, after creating issue (as usually, lol).

Sure, `colors.js` is pretty much what such projects need - list of color definitions.
To make work more convenient I would wrap them into reusable style definitions - in a separate package, I think.
