### ISSUE TITLE
Adding colors

### ISSUE THREAD

**Issue by akash-vartak** [mrmrs/colors#106]
I want to add colors, specifically, light versions of already present ones, and some new colors. For this could you point me towards any other file that needs to be updated other than `css/color.css` , `css/color.min.css` and `README.md`.

**Comment by mrmrs** [comment]
@akash-vartak not taking any additional colors to this repo but if you are building your  own custom version and you want to be able to access colors from javascript you can change this file as well:

https://github.com/mrmrs/colors/blob/master/js/colors.js

Cheers
