### ISSUE TITLE
Repo has been removed from Google search results by bad DMCA takedown notice

### ISSUE THREAD

**Issue by cvrebert** [mrmrs/colors#62]
FYI, this repo is URL number 403 on https://www.chillingeffects.org/notices/10275257
Context: https://news.ycombinator.com/item?id=8848544

**Comment by cvrebert** [comment]
Apparently @mrmrs is corrupting the nation's youth and the town's pleasantness through his promotion of these vibrant colors. "Fuchsia"? More like "Fuck Sia". /s

**Comment by DomT4** [comment]
Companies really should face hefty fines for bullshit DMCA notices. What a bunch of nonsense that takedown is.

**Comment by DaAwesomeP** [comment]
It seems to be back on Google: [Google search: mrmrs colors](http://lmgtfy.com/?q=mrmrs+colors).

**Comment by cvrebert** [comment]
Yay! I'm pretty sure mrmrs could probably sue for some damages if he wanted, but that's beyond the direct scope of this bug.
