### ISSUE TITLE
Create preset color combinations 

### ISSUE THREAD

**Issue by jlina09640** [mrmrs/colors#71]
I was looking at the CSS files and I was thinking about creating a CSS file that would have presets. This would just mean that there would be multiple preset classes where there would be one particular background color (such as navy, white, blue, red etc) then the font, border, strokes, fills colors would just be another color. 

The combinations could be utilized from the colorable website provided in your website, let me know what you think!

**Comment by mrmrs** [comment]
@jlina09640 - I don't think I understand what you mean. Can you please elaborate further?

**Comment by jlina09640** [comment]
Sorry!
![screen shot 2015-03-23 at 8 31 17 am](https://cloud.githubusercontent.com/assets/9473780/6779919/fddbdcb0-d136-11e4-999c-57d934f4255b.png)

Here's a screenshot that will hopefully elaborate what I was trying to say better. It's basically a CSS files with classes that would have different background colors paired with another color for the fonts and whatnot. I thought it would be a simple but useful idea.

**Comment by mrmrs** [comment]
Ah yes I see. I don't want that as a part of this repo - but you are welcome to make this your own project!
This project is meant to just be the single purpose classes. 
I'd suggest only making combinations that are accessible - you can see all of those at 
http://jxnblk.com/colorable

Thanks!
