### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by jamiesonbecker** [mrmrs/colors#72]
It looks like headers indicate MIT (awesome!) but there seems to be no LICENSE file.

Thanks mrmrs!!

**Comment by tcarlsen** [comment]
bottom of [README](https://github.com/mrmrs/colors#license)

**Comment by ilanbiala** [comment]
#73 should fix this.

**Comment by mrmrs** [comment]
Added a license.md - thanks for bringing this up @jamiesonbecker
