### ISSUE TITLE
atom package

### ISSUE THREAD

**Issue by tcarlsen** [mrmrs/colors#74]
Just wanted to let you know that I :heart:  this package and the colors in it. I use it all the time then prototyping or coding on my own projects with no designer.

But I wanted an even easier way to access these awesome colors so I made a package for my favorite text editor, [Atom](https://atom.io). I hope you like this Idea and are totally okay with it?

The package is located here: https://atom.io/packages/colors

**Comment by mrmrs** [comment]
@tcarlsen It's open source! You're totally allowed to package it up however you want. I'll add a link to it on the project page.

**Comment by tcarlsen** [comment]
that would be awesome... thx m8! :baby_chick:
