### ISSUE TITLE
the more obscure color codes

### ISSUE THREAD

**Issue by chriddyp** [mrmrs/colors#75]
i love love love this! i was wondering if you had thoughts, or references, about creating a nicer palate around the rest of the ~130 colors, e.g. `khaki`, `lightgray`, `salmon`. i'm working on a graphing library and would love for users to be able to drop human-readable color IDs with nicer colors :)

**Comment by enociz** [comment]
I think this is a good idea so +1

**Comment by enociz** [comment]
Also, I would like to encourage people out there with an eye for colours to contribute via pull requests to help this cause of expanding from just the base colours

**Comment by enche** [comment]
At what point should the colors be branched off into an "extras" file? It's less than 1KB right now, so tons of colors could be added without most people minding... but a focal point of the project is its simplicity, too.

Maybe there's a better spot for my meta discussion.

**Comment by enociz** [comment]
Oh yeah, that's a good point. Simplicity is key.

**Comment by mrmrs** [comment]
I think a larger color palette would be really cool but a separate project from this one. If it's something you'd like to attack @chriddyp feel free to fork this as a base or just start a new project on your own. Don't know when I'd get around to it myself but something I've thought about a few times :)
