### ISSUE TITLE
Refusing to install colors.css as a dependency of itself

### ISSUE THREAD

**Issue by mromanoff** [mrmrs/colors#89]
running  npm install --save-dev colors.css
I'm getting this error: Refusing to install colors.css as a dependency of itself
my npm -v 3.3.12

**Comment by mrmrs** [comment]
@mromanoff where are you running that command? Inside the colors repo directory or a separate project?

**Comment by mrmrs** [comment]
Closing this out due to inactivity but feel free to reopen if it is still an issue.
