### ISSUE TITLE
Variables not in css/colors.css

### ISSUE THREAD

**Issue by erickmerchant** [mrmrs/colors#91]
So when I `@import "colors.css";` I don't get the variables in src/_variables.css. As a work around I can just `@import "colors.css/src/colors.css";`. I'm just not clear if this intended or not. Thanks.

**Comment by mrmrs** [comment]
@erickmerchant Good question. I *believe* if you want the variables - your suggested workaround is the best option. I just intended the default import to be static css, but maybe your use case is more common.
