### ISSUE TITLE
Swatch for Affinity

### ISSUE THREAD

**Issue by victorzimmer** [mrmrs/colors#92]
There was no swatch available for download to use with Affinity software (none that I could find at least).
So here is one!

[https://www.dropbox.com/s/mcgc1f3pgucx9yu/Clrs.cc.clr?dl=0](https://www.dropbox.com/s/mcgc1f3pgucx9yu/Clrs.cc.clr?dl=0)

**Comment by mrmrs** [comment]
Thanks! Will add this.

**Comment by victorzimmer** [comment]
Awesome!
